import numpy as np

from retriever.core.types import (
    NLCommand,
    ObjectSymbol,
    ObjectVariable,
    Observation,
    RGBDImage,
)
from retriever.grounding.dynamic_grounding import DynamicGroundingModule
from retriever.models.perception_module import PerceptionModule
from retriever.models.segmentation.pointing_gemini_sam2_client import (
    PointingGeminiSAM2Client,
)


class MockPerceptionClient(PointingGeminiSAM2Client):
    """
    A mock client that returns a canned response simulating the detection
    of two cups and one mug.
    """

    def predict(self, *args, **kwargs):
        return {
            "results": [
                {
                    "labels": ["red cup", "blue mug", "red cup"],
                }
            ],
            "timings": {},
        }


def test_perception_to_grounding_pipeline():
    """
    Tests the full data flow from PerceptionModule to DynamicGroundingModule.
    """
    # 1. Setup: Instantiate all modules in the pipeline.
    # The mock client will provide a fixed perception result.
    mock_client = MockPerceptionClient(host="dummy", port=0)
    perception_module = PerceptionModule(client=mock_client)
    grounding_module = DynamicGroundingModule()

    # 2. Input: Define the initial inputs for the pipeline.
    # This simulates a user asking to find two cups.
    command = NLCommand(text="find the two red cups")
    # A dummy observation is sufficient since the client is mocked.
    dummy_rgbd = RGBDImage(
        rgb=np.zeros((10, 10, 3), dtype=np.uint8), depth=np.zeros((10, 10))
    )
    observation = Observation(images={"front_camera": dummy_rgbd})

    # 3. Perception Step: Run the perception module.
    # This converts the raw observation into a list of described objects.
    _, object_descriptions = perception_module((observation, command))

    # This simulates the part of the system that would parse the NL command
    # into a symbolic query. For "find two red cups", this would be two
    # variables of type "cup".
    query_variables = [ObjectVariable(name="cup"), ObjectVariable(name="cup")]

    # 4. Grounding Step: Run the grounding module.
    # This maps the symbolic query to the perceived objects.
    grounded_symbols = grounding_module((query_variables, object_descriptions))

    # 5. Assertions: Verify the final output is correct.
    # The pipeline should have successfully identified and grounded both cups.
    assert len(grounded_symbols) == 2

    # The specific IDs are generated by the perception module. We check that
    # the grounded symbols correspond to the two cups.
    expected_ids = ["red_cup_0", "red_cup_2"]
    actual_ids = sorted([s.object_id for s in grounded_symbols])
    assert actual_ids == expected_ids 